### ISSUE TITLE
Enable extdiff with git globally

### ISSUE THREAD

**Issue by tangoalx** [ForNeVeR/ExtDiff#8]
At the moment, you must configure each repository to pass the diff to ms word, since you need to copy the **.gitattributes** file in the repository. 

However, there is a possibility to make it available globally for all projects of a user. You can copy the .gitattributes file into the user's home directory instead into your projects root directory. Git need to know the location of that file. You can set it and check if the path is correctly expanded to the location where you copied the **.gitattributes** file:

```
git config --global core.attributesfile ~/.gitattributes
git config --global core.attributesfile
```

I suggest to update the [README.MD](../blob/0187fbfebd0fd0d9de6abb763aa8689b691deddd/Readme.md) to help also user's who are inexperienced with git.

Thanks by the way for that really cool tool.

**Comment by ForNeVeR** [comment]
Thank you, this is a good suggestion. I wasn't aware of the global `.gitattributes` myself, so this will help me to save a bit of typing :)
